#!/bin/bash

cd /home/pi/Desktop/v2v

#pip3 install netifaces obd

# Networking
cp etc-network-interfaces.d/bat0.example etc-network-interfaces.d/bat0
chown pi:pi etc-network-interfaces.d/bat0
ln -sf "$(pwd)/etc-network/interfaces"         /etc/network/interfaces
ln -sf "$(pwd)/etc-network-interfaces.d/bat0"  /etc/network/interfaces.d/bat0
ln -sf "$(pwd)/etc-network-interfaces.d/wlan0" /etc/network/interfaces.d/wlan0

# Services
ln -sf "$(pwd)/lib-systemd-system/v2v-batman.service"        /lib/systemd/system/v2v-batman.service
ln -sf "$(pwd)/lib-systemd-system/v2v-obd2rpi.service"       /lib/systemd/system/v2v-obd2rpi.service
ln -sf "$(pwd)/lib-systemd-system/v2v-vehicleclient.service" /lib/systemd/system/v2v-vehicleclient.service
ln -sf "$(pwd)/lib-systemd-system/v2v-vehicleserver.service" /lib/systemd/system/v2v-vehicleserver.service
mkdir -p lib-systemd-system/log
chown pi:pi lib-systemd-system/log
systemctl daemon-reload
systemctl enable v2v-batman.service
systemctl enable v2v-obd2rpi.service
systemctl enable v2v-vehicleclient.service
systemctl enable v2v-vehicleserver.service

# vehicleinfo.txt
cp vehicleinfo.txt.example vehicleinfo.txt
chown pi:pi vehicleinfo.txt

# Tasks
echo "Úlohy:"
echo "------"
echo "1. V súbore ./etc-network-interfaces.d/bat0 oprav IP adresu"
echo "2. V súbore ./vehicleinfo.txt oprav údaje o aute"
